import { CalendarDays, MapPin, UserRound } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { getFixture } from "@/lib/service/competition.service";
import { getFixtureSetup } from "@/lib/service/competition.service";
import { FixtureManagement } from "@/components/matches/fixture-management";

export default async function MatchesPage() {
  const [matches, setup] = await Promise.all([getFixture(), getFixtureSetup()]);
  return <AppShell><div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold tracking-[.18em] text-[var(--ea-gold)]">COMPETENCIA</p><h1 className="mt-1 text-3xl text-white">Fixture</h1><p className="mt-1 text-sm text-stone-400">Calendario de partidos y resultados cargados.</p></div><FixtureManagement setup={setup} /></div><section className="ea-panel overflow-hidden rounded-lg"><div className="flex items-center justify-between border-b border-[var(--ea-border)] p-5"><h2 className="ea-heading text-xl">Partidos programados</h2><span className="rounded bg-[#2b2010] px-3 py-1 text-sm text-[var(--ea-gold)]">{matches.length} encuentros</span></div>{matches.length ? <div className="divide-y divide-[var(--ea-border)]">{matches.map((match) => <article key={match.id} className="grid gap-3 p-5 lg:grid-cols-[9rem_1fr_auto_1fr_12rem]"><div className="text-sm"><p className="font-semibold text-[var(--ea-gold-soft)]">Fecha {match.round ?? "-"}</p><p className="mt-1 text-stone-400">{match.match_date ? new Date(`${match.match_date}T00:00:00`).toLocaleDateString("es-AR") : "Sin fecha"}</p><p className="text-stone-500">{match.kickoff_time?.slice(0, 5) ?? "--:--"}</p></div><strong className="self-center text-right text-base">{match.home_team ?? "Por definir"}</strong><span className="self-center rounded border border-[var(--ea-gold)]/30 px-3 py-1 text-center font-bold text-[var(--ea-gold)]">{match.home_score ?? 0} - {match.away_score ?? 0}</span><strong className="self-center text-base">{match.away_team ?? "Por definir"}</strong><div className="self-center text-xs text-stone-500"><p className="flex gap-1"><MapPin size={14} />{match.field ?? "Cancha a definir"}</p><p className="mt-1 flex gap-1"><UserRound size={14} />{match.referee ?? "Sin arbitro"}</p></div></article>)}</div> : <Empty text="Cuando generes el fixture, los partidos apareceran aqui." />}</section></div></AppShell>;
}
function Empty({ text }: { text: string }) { return <div className="grid min-h-60 place-items-center p-8 text-center"><div><CalendarDays className="mx-auto h-9 w-9 text-[var(--ea-gold)]" /><p className="mt-3 text-sm text-stone-400">{text}</p></div></div>; }
