import Link from "next/link";
import { ArrowLeft, UserRound } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { getTeamRoster } from "@/lib/service/team.service";

export default async function TeamRosterPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const { team, players } = await getTeamRoster(id);
  return <AppShell><div className="space-y-6"><Link href="/teams" className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--ea-gold)]"><ArrowLeft size={16} />Volver a equipos</Link><div className="flex items-center gap-4">{team.logo_url ? <img src={team.logo_url} alt="" className="h-16 w-16 rounded-lg object-contain" /> : <div className="grid h-16 w-16 place-items-center rounded-lg border border-[var(--ea-gold)]/40"><UserRound className="text-[var(--ea-gold)]" /></div>}<div><p className="text-xs font-bold tracking-[.18em] text-[var(--ea-gold)]">LISTA DE BUENA FE</p><h1 className="mt-1 text-3xl text-white">Plantel · {team.name}</h1><p className="mt-1 text-sm text-stone-400">{players.length} jugadores asignados actualmente.</p></div></div><section className="ea-panel overflow-hidden rounded-lg">{players.length ? <div className="divide-y divide-[var(--ea-border)]">{(players as unknown as Array<{ id: string; shirt_number: number; is_captain: boolean; is_goalkeeper: boolean; players: { first_name: string; last_name: string; document_number: string; photo_url: string | null } | null }>).map((entry) => <article key={entry.id} className="flex items-center gap-4 p-4"><span className="grid h-10 w-10 place-items-center rounded-md bg-[#29180d] font-bold text-[var(--ea-gold)]">#{entry.shirt_number}</span>{entry.players?.photo_url ? <img src={entry.players.photo_url} alt="" className="h-10 w-10 rounded-full object-cover" /> : <UserRound className="h-8 w-8 text-stone-500" />}<div><p className="font-semibold">{entry.players?.first_name} {entry.players?.last_name}</p><p className="text-xs text-stone-500">DNI: {entry.players?.document_number}</p></div><div className="ml-auto flex gap-2 text-xs">{entry.is_captain && <span className="rounded bg-[#9e171b] px-2 py-1">Capitán</span>}{entry.is_goalkeeper && <span className="rounded bg-[#a66b0e] px-2 py-1">Arquero</span>}</div></article>)}</div> : <p className="p-12 text-center text-sm text-stone-500">Todavía no hay jugadores asignados a este equipo.</p>}</section></div></AppShell>;
}
