import { CreditCard, ReceiptText } from "lucide-react";
import { AppShell } from "@/components/layout/AppShell";
import { getPayments } from "@/lib/service/competition.service";

const money = new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS", maximumFractionDigits: 0 });

export default async function PaymentsPage() {
  const payments = await getPayments();
  const total = payments.reduce((sum, payment) => sum + Number(payment.amount ?? 0), 0);
  return <AppShell><div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold tracking-[.18em] text-[var(--ea-gold)]">ADMINISTRACION</p><h1 className="mt-1 text-3xl text-white">Pagos</h1><p className="mt-1 text-sm text-stone-400">Control de cuotas, inscripciones y comprobantes.</p></div><div className="rounded-lg border border-[var(--ea-gold)]/30 bg-[#251b0e] px-5 py-3"><p className="text-xs text-stone-400">Total registrado</p><p className="text-xl font-bold text-[var(--ea-gold-soft)]">{money.format(total)}</p></div></div><section className="ea-panel overflow-hidden rounded-lg">{payments.length ? <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="border-b border-[var(--ea-border)] text-left text-xs uppercase tracking-wider text-stone-500"><tr><th className="p-4">Equipo</th><th>Concepto</th><th>Vencimiento</th><th>Importe</th><th>Estado</th><th>Comprobante</th></tr></thead><tbody>{payments.map((payment) => { const status = payment.payment_statuses?.[0]; return <tr key={payment.id} className="border-b border-[var(--ea-border)]/70"><td className="p-4 font-semibold">{payment.team_category_registrations?.[0]?.display_name ?? "Equipo"}</td><td>{payment.payment_types?.[0]?.name ?? "Pago"}</td><td className="text-stone-400">{payment.due_date ? new Date(`${payment.due_date}T00:00:00`).toLocaleDateString("es-AR") : "-"}</td><td className="font-semibold">{money.format(Number(payment.amount))}</td><td><span className={`rounded px-2 py-1 text-xs font-bold ${status?.code === "PAID" ? "bg-green-900/50 text-green-300" : "bg-amber-900/50 text-amber-200"}`}>{status?.name ?? "Pendiente"}</span></td><td className="text-stone-400">{payment.receipt_number ?? "-"}</td></tr>; })}</tbody></table></div> : <Empty text="Todavia no hay pagos registrados." />}</section></div></AppShell>;
}
function Empty({ text }: { text: string }) { return <div className="grid min-h-60 place-items-center p-8 text-center"><div><CreditCard className="mx-auto h-9 w-9 text-[var(--ea-gold)]" /><p className="mt-3 text-sm text-stone-400">{text}</p><ReceiptText className="mx-auto mt-3 h-4 w-4 text-stone-600" /></div></div>; }
