"use client";

import { useState } from "react";
import { MapPin, Plus, Trash2, UserRound } from "lucide-react";
import { toast } from "sonner";
import { createField, createReferee, deleteField, deleteReferee } from "@/lib/actions/settings";
import type { FieldSetup, RefereeSetup } from "@/lib/service/settings.service";

export function FixtureResources({ initialFields, initialReferees }: { initialFields: FieldSetup[]; initialReferees: RefereeSetup[] }) {
  const [fields, setFields] = useState(initialFields);
  const [referees, setReferees] = useState(initialReferees);
  const [fieldName, setFieldName] = useState("");
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [loading, setLoading] = useState<string | null>(null);

  async function addField(event: React.FormEvent) { event.preventDefault(); setLoading("field"); try { const field = await createField({ name: fieldName }); setFields((current) => [...current, field].sort((a, b) => a.name.localeCompare(b.name))); setFieldName(""); toast.success("Cancha creada."); } catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo crear la cancha."); } finally { setLoading(null); } }
  async function addReferee(event: React.FormEvent) { event.preventDefault(); setLoading("referee"); try { const referee = await createReferee({ first_name: firstName, last_name: lastName }); setReferees((current) => [...current, referee].sort((a, b) => a.last_name.localeCompare(b.last_name))); setFirstName(""); setLastName(""); toast.success("Árbitro creado."); } catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo crear el árbitro."); } finally { setLoading(null); } }
  async function removeField(field: FieldSetup) { if (!window.confirm(`¿Dar de baja la cancha “${field.name}”? Los partidos ya cargados conservarán su historial.`)) return; setLoading(field.id); try { await deleteField(field.id); setFields((current) => current.filter((item) => item.id !== field.id)); toast.success("Cancha dada de baja."); } catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo dar de baja la cancha."); } finally { setLoading(null); } }
  async function removeReferee(referee: RefereeSetup) { const name = `${referee.first_name} ${referee.last_name}`; if (!window.confirm(`¿Dar de baja al árbitro “${name}”? Los partidos ya cargados conservarán su historial.`)) return; setLoading(referee.id); try { await deleteReferee(referee.id); setReferees((current) => current.filter((item) => item.id !== referee.id)); toast.success("Árbitro dado de baja."); } catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo dar de baja al árbitro."); } finally { setLoading(null); } }

  return <section className="grid gap-5 lg:grid-cols-2"><article className="ea-panel rounded-lg p-5"><div className="flex items-center gap-2"><MapPin className="text-[var(--ea-gold)]" /><div><h2 className="ea-heading text-xl">Canchas</h2><p className="text-sm text-stone-400">Disponibles al programar partidos.</p></div></div><form onSubmit={addField} className="mt-4 flex gap-2"><input required value={fieldName} onChange={(event) => setFieldName(event.target.value)} placeholder="Ej. Cancha principal" /><button disabled={loading !== null} className="inline-flex shrink-0 items-center gap-1 rounded-md bg-[linear-gradient(135deg,#b71920,#77080d)] px-3 py-2 text-sm font-bold text-white disabled:opacity-50"><Plus size={15} />Agregar</button></form><div className="mt-4 divide-y divide-[var(--ea-border)] rounded border border-[var(--ea-border)]">{fields.length ? fields.map((field) => <div key={field.id} className="flex items-center justify-between gap-3 p-3 text-sm"><span>{field.name}</span><button disabled={loading === field.id} onClick={() => removeField(field)} aria-label={`Eliminar ${field.name}`} className="rounded border border-red-900/70 p-1.5 text-red-300 hover:bg-red-950/40 disabled:opacity-50"><Trash2 size={14} /></button></div>) : <p className="p-3 text-sm text-stone-500">Todavía no hay canchas cargadas.</p>}</div></article><article className="ea-panel rounded-lg p-5"><div className="flex items-center gap-2"><UserRound className="text-[var(--ea-gold)]" /><div><h2 className="ea-heading text-xl">Árbitros</h2><p className="text-sm text-stone-400">Disponibles al programar partidos.</p></div></div><form onSubmit={addReferee} className="mt-4 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><input required value={firstName} onChange={(event) => setFirstName(event.target.value)} placeholder="Nombre" /><input required value={lastName} onChange={(event) => setLastName(event.target.value)} placeholder="Apellido" /><button disabled={loading !== null} className="inline-flex items-center justify-center gap-1 rounded-md bg-[linear-gradient(135deg,#b71920,#77080d)] px-3 py-2 text-sm font-bold text-white disabled:opacity-50"><Plus size={15} />Agregar</button></form><div className="mt-4 divide-y divide-[var(--ea-border)] rounded border border-[var(--ea-border)]">{referees.length ? referees.map((referee) => <div key={referee.id} className="flex items-center justify-between gap-3 p-3 text-sm"><span>{referee.last_name}, {referee.first_name}</span><button disabled={loading === referee.id} onClick={() => removeReferee(referee)} aria-label={`Eliminar ${referee.first_name}`} className="rounded border border-red-900/70 p-1.5 text-red-300 hover:bg-red-950/40 disabled:opacity-50"><Trash2 size={14} /></button></div>) : <p className="p-3 text-sm text-stone-500">Todavía no hay árbitros cargados.</p>}</div></article></section>;
}
