"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import type { DashboardCatalog } from "@/lib/service/dashboard.service";

type FixtureFilter = { tournamentId?: string; categoryId?: string; zoneId?: string; phaseId?: string; round?: string };
type Props = { catalog: DashboardCatalog; phases: { id: string; name: string }[]; rounds: number[]; filter: FixtureFilter };

export function FixtureFilters({ catalog, phases, rounds, filter }: Props) {
  const router = useRouter(); const [pending, startTransition] = useTransition();
  const [tournamentId, setTournamentId] = useState(filter.tournamentId ?? ""); const [categoryId, setCategoryId] = useState(filter.categoryId ?? ""); const [zoneId, setZoneId] = useState(filter.zoneId ?? ""); const [phaseId, setPhaseId] = useState(filter.phaseId ?? ""); const [round, setRound] = useState(filter.round ?? "");
  const categories = useMemo(() => catalog.categories.filter((item) => item.tournament_id === tournamentId), [catalog.categories, tournamentId]);
  const zones = useMemo(() => catalog.zones.filter((item) => item.category_id === categoryId), [catalog.zones, categoryId]);
  function navigate(next: FixtureFilter) { const params = new URLSearchParams(); if (next.tournamentId) params.set("tournament", next.tournamentId); if (next.categoryId) params.set("category", next.categoryId); if (next.zoneId) params.set("zone", next.zoneId); if (next.phaseId) params.set("phase", next.phaseId); if (next.round) params.set("round", next.round); startTransition(() => router.push(`/matches${params.size ? `?${params}` : ""}`)); }
  return <div className="ea-panel grid gap-3 rounded-lg p-4 md:grid-cols-5"><select aria-label="Torneo" value={tournamentId} onChange={(event) => { const value = event.target.value; setTournamentId(value); setCategoryId(""); setZoneId(""); setRound(""); navigate({ tournamentId: value, phaseId }); }}><option value="">Todos los torneos</option>{catalog.tournaments.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Categoría" disabled={!tournamentId} value={categoryId} onChange={(event) => { const value = event.target.value; setCategoryId(value); setZoneId(""); setRound(""); navigate({ tournamentId, categoryId: value, phaseId }); }}><option value="">{tournamentId ? "Todas las categorías" : "Elegí primero un torneo"}</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Zona" disabled={!categoryId} value={zoneId} onChange={(event) => { const value = event.target.value; setZoneId(value); setRound(""); navigate({ tournamentId, categoryId, zoneId: value, phaseId }); }}><option value="">{categoryId ? "Todas las zonas" : "Elegí primero una categoría"}</option>{zones.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Fase" value={phaseId} onChange={(event) => { const value = event.target.value; setPhaseId(value); setRound(""); navigate({ tournamentId, categoryId, zoneId, phaseId: value }); }}><option value="">Todas las fases</option>{phases.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select aria-label="Fecha" disabled={!categoryId} value={round} onChange={(event) => { const value = event.target.value; setRound(value); navigate({ tournamentId, categoryId, zoneId, phaseId, round: value }); }}><option value="">{categoryId ? "Todas las fechas" : "Elegí torneo y categoría"}</option>{rounds.map((item) => <option key={item} value={String(item)}>Fecha {item}</option>)}</select><p className="md:col-span-5 text-right text-xs text-stone-500">{pending ? "Actualizando…" : "Zona es opcional: usala para la fase regular; Play Off se consulta por torneo y categoría."}</p></div>;
}
