"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Check, ClipboardCheck, Pencil, Plus, Search, ScrollText } from "lucide-react";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { cancelPreliminarySheet, confirmSheet, finishMatchSheet, saveMatchEvent, saveSheetEntry, setSheetStatus, updateSheetEvent } from "@/lib/actions/match-events";
import type { MatchReport } from "@/lib/service/competition.service";

type ConfirmationType = "REFEREE" | "SUPERVISOR" | "HOME_DELEGATE" | "AWAY_DELEGATE";
const labels: Record<ConfirmationType, string> = { HOME_DELEGATE: "Delegado local", AWAY_DELEGATE: "Delegado visitante", REFEREE: "Árbitro", SUPERVISOR: "Veedor" };

export function MatchEventsClient({ report }: { report: MatchReport }) {
  const [teamId, setTeamId] = useState(report.homeTeamRegistrationId);
  const [search, setSearch] = useState("");
  const [savingId, setSavingId] = useState<string | null>(null);
  const [eventPlayerId, setEventPlayerId] = useState("");
  const [eventTypeId, setEventTypeId] = useState("");
  const [editingPlayer, setEditingPlayer] = useState<MatchReport["players"][number] | null>(null);
  const [editingEvent, setEditingEvent] = useState<MatchReport["events"][number] | null>(null);
  const [confirmationType, setConfirmationType] = useState<ConfirmationType | null>(null);
  const [loading, setLoading] = useState(false);
  const entries = new Map(report.sheetEntries.map((entry) => [entry.playerRegistrationId, entry]));
  const players = useMemo(() => report.players.filter((player) => player.teamRegistrationId === teamId && `${player.name} ${player.documentNumber ?? ""}`.toLowerCase().includes(search.trim().toLowerCase())), [report.players, search, teamId]);
  const eventPlayers = report.players.filter((player) => entries.get(player.id)?.isPresent);
  const teamName = teamId === report.homeTeamRegistrationId ? report.homeTeam : report.awayTeam;
  const editable = report.sheetStatus === "OPEN" && report.permissions.canEditSheet && !report.matchFinishedAt;
  const manageable = report.permissions.canManageSheet;
  const editingEntry = editingPlayer ? entries.get(editingPlayer.id) : null;
  const has = (type: ConfirmationType) => report.confirmations.some((item) => item.confirmationType === type);
  const delegatesConfirmed = has("HOME_DELEGATE") && has("AWAY_DELEGATE");
  const confirmationTypes: ConfirmationType[] = report.officials.supervisor ? ["HOME_DELEGATE", "AWAY_DELEGATE", "REFEREE", "SUPERVISOR"] : ["HOME_DELEGATE", "AWAY_DELEGATE", "REFEREE"];

  async function saveEntry(player: MatchReport["players"][number], values: { shirtNumber: number; isPresent: boolean; isCaptain: boolean; isGoalkeeper: boolean; isStarter: boolean; notes?: string }) {
    await saveSheetEntry({ matchId: report.id, playerRegistrationId: player.id, teamRegistrationId: player.teamRegistrationId, ...values });
  }
  async function togglePlayer(player: MatchReport["players"][number]) {
    setSavingId(player.id); const entry = entries.get(player.id);
    try { await saveEntry(player, { shirtNumber: entry?.shirtNumber ?? player.shirtNumber, isPresent: !entry?.isPresent, isCaptain: entry?.isCaptain ?? false, isGoalkeeper: entry?.isGoalkeeper ?? false, isStarter: entry?.isStarter ?? false, notes: entry?.notes ?? "" }); toast.success(!entry?.isPresent ? `${player.name} marcado presente.` : `${player.name} marcado ausente.`); }
    catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo actualizar la planilla."); } finally { setSavingId(null); }
  }
  async function savePlayerDetails(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!editingPlayer) return; const form = new FormData(event.currentTarget); const entry = entries.get(editingPlayer.id); setSavingId(editingPlayer.id);
    try { await saveEntry(editingPlayer, { shirtNumber: Number(form.get("shirtNumber")), isPresent: entry?.isPresent ?? false, isCaptain: form.get("isCaptain") === "on", isGoalkeeper: form.get("isGoalkeeper") === "on", isStarter: form.get("isStarter") === "on", notes: entry?.notes ?? "" }); toast.success("Datos de planilla actualizados."); setEditingPlayer(null); }
    catch (error) { toast.error(error instanceof Error ? error.message : "No se pudieron guardar los datos."); } finally { setSavingId(null); }
  }
  async function submitEvent(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoading(true); const form = new FormData(event.currentTarget);
    try { await saveMatchEvent({ matchId: report.id, playerRegistrationId: eventPlayerId, eventTypeId, minute: Number(form.get("minute")), comments: String(form.get("comments") ?? "") }); setEventPlayerId(""); setEventTypeId(""); event.currentTarget.reset(); toast.success("Evento registrado."); }
    catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo registrar el evento."); } finally { setLoading(false); }
  }
  async function submitEventEdit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!editingEvent) return; const form = new FormData(event.currentTarget); setLoading(true);
    try { await updateSheetEvent({ id: editingEvent.id, matchId: report.id, playerRegistrationId: String(form.get("playerRegistrationId")), eventTypeId: String(form.get("eventTypeId")), minute: Number(form.get("minute")), comments: String(form.get("comments") ?? "") }); toast.success("Evento corregido."); setEditingEvent(null); }
    catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo actualizar el evento."); } finally { setLoading(false); }
  }
  async function confirm(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!confirmationType) return; const form = new FormData(event.currentTarget); setLoading(true);
    try { await confirmSheet({ matchId: report.id, confirmationType, comments: String(form.get("comments") ?? "") }); toast.success("Confirmación digital registrada."); setConfirmationType(null); }
    catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo confirmar la planilla."); } finally { setLoading(false); }
  }
  async function changeStatus(status: "DRAFT" | "OPEN" | "CLOSED") { try { await setSheetStatus({ matchId: report.id, status }); toast.success(status === "DRAFT" ? "Planilla preliminar creada." : status === "OPEN" ? "Planilla abierta." : "Planilla cerrada."); } catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo cambiar el estado."); } }
  async function cancelPreliminary() { if (!window.confirm("¿Cancelar la planilla preliminar? Se quitará la convocatoria precargada.")) return; setLoading(true); try { await cancelPreliminarySheet({ matchId: report.id }); toast.success("Planilla preliminar cancelada."); } catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo cancelar la planilla."); } finally { setLoading(false); } }
  async function finishMatch() { if (!window.confirm("¿Marcar el partido como finalizado? Ya no se podrán modificar jugadores ni eventos antes de las conformidades.")) return; setLoading(true); try { await finishMatchSheet({ matchId: report.id }); toast.success("Partido finalizado. Ya pueden confirmar los delegados."); } catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo finalizar el partido."); } finally { setLoading(false); } }
  function canConfirm(type: ConfirmationType) { if (report.sheetStatus !== "OPEN" || !report.matchFinishedAt) return false; if (type === "HOME_DELEGATE") return report.permissions.canConfirmHomeDelegate; if (type === "AWAY_DELEGATE") return report.permissions.canConfirmAwayDelegate; if (type === "REFEREE") return report.permissions.canConfirmOfficials && delegatesConfirmed; return report.permissions.canConfirmOfficials && delegatesConfirmed && has("REFEREE"); }

  return <div className="space-y-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold tracking-[.18em] text-[var(--ea-gold)]">PLANILLA DIGITAL</p><h1 className="mt-1 text-2xl text-white sm:text-3xl">{report.homeTeam} vs. {report.awayTeam}</h1><p className="mt-1 text-sm text-stone-400">Convocatoria, eventos y constancias desde el teléfono.</p></div><Link href="/matches" className="inline-flex items-center gap-2 rounded-md border border-[var(--ea-border)] px-3 py-2 text-sm font-bold text-stone-200"><ArrowLeft size={16} />Volver al fixture</Link></div>
    <section className="ea-panel rounded-lg p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="ea-heading text-lg">Estado: {report.sheetStatus === "DRAFT" ? "Preliminar" : report.sheetStatus === "OPEN" ? report.matchFinishedAt ? "Partido finalizado" : "Abierta" : report.sheetStatus === "CLOSED" ? "Cerrada" : "Sin iniciar"}</p><p className="text-xs text-stone-400">La primera etapa precarga ambos planteles.</p></div><div className="flex flex-wrap gap-2">{manageable && <>{!report.sheetStatus && <button onClick={() => changeStatus("DRAFT")} className="rounded-md border border-[var(--ea-gold)]/50 px-3 py-2 text-xs font-bold">Crear preliminar</button>}{report.sheetStatus === "DRAFT" && <><button disabled={loading} onClick={cancelPreliminary} className="rounded-md border border-red-900/70 px-3 py-2 text-xs font-bold text-red-200">Cancelar preliminar</button><button disabled={loading} onClick={() => changeStatus("OPEN")} className="rounded-md bg-[#9e1016] px-3 py-2 text-xs font-bold text-white">Abrir para árbitro</button></>}{report.sheetStatus === "OPEN" && report.matchFinishedAt && <button onClick={() => changeStatus("CLOSED")} className="rounded-md bg-[#9e1016] px-3 py-2 text-xs font-bold text-white">Cerrar planilla</button>}{report.sheetStatus === "CLOSED" && <button onClick={() => changeStatus("OPEN")} className="rounded-md border border-[var(--ea-gold)]/50 px-3 py-2 text-xs font-bold text-[var(--ea-gold-soft)]">Reabrir (administración)</button>}</>}{report.sheetStatus === "OPEN" && !report.matchFinishedAt && report.permissions.canEditSheet && <button disabled={loading} onClick={finishMatch} className="rounded-md bg-[#9e1016] px-3 py-2 text-xs font-bold text-white">Partido finalizado</button>}</div></div></section>
    <section className="ea-panel rounded-lg p-3 sm:p-5"><div className="grid grid-cols-2 gap-2"><button onClick={() => { setTeamId(report.homeTeamRegistrationId); setSearch(""); }} className={`rounded-md px-3 py-3 text-sm font-bold ${teamId === report.homeTeamRegistrationId ? "bg-[#9e1016] text-white" : "border border-[var(--ea-border)]"}`}>{report.homeTeam}</button><button onClick={() => { setTeamId(report.awayTeamRegistrationId); setSearch(""); }} className={`rounded-md px-3 py-3 text-sm font-bold ${teamId === report.awayTeamRegistrationId ? "bg-[#9e1016] text-white" : "border border-[var(--ea-border)]"}`}>{report.awayTeam}</button></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="ea-heading text-xl">{teamName}</h2><p className="text-xs text-stone-400">{players.filter((player) => entries.get(player.id)?.isPresent).length}/{players.length} presentes</p></div><label className="relative block"><Search className="absolute left-3 top-2.5 text-stone-500" size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} className="w-64 pl-9" placeholder="Buscar por DNI o nombre" /></label></div><div className="mt-3 divide-y divide-[var(--ea-border)] overflow-hidden rounded-md border border-[var(--ea-border)]">{players.map((player) => { const entry = entries.get(player.id); const present = entry?.isPresent ?? false; return <div key={player.id} className="flex items-center gap-2 p-3"><button disabled={!editable || savingId === player.id} onClick={() => togglePlayer(player)} className="flex min-w-0 flex-1 items-center gap-3 text-left disabled:opacity-50"><span className="grid h-8 w-8 shrink-0 place-items-center rounded border border-[var(--ea-gold)]/40 text-sm font-bold text-[var(--ea-gold)]">{entry?.shirtNumber ?? player.shirtNumber}</span><span className="min-w-0 flex-1"><span className="block font-semibold">{player.firstName} {player.lastName}{entry?.isStarter ? " · TIT" : ""}{entry?.isCaptain ? " · C" : ""}{entry?.isGoalkeeper ? " · ARQ" : ""}</span><span className="block text-xs text-stone-400">DNI {player.documentNumber ?? "sin cargar"} · Nac. {player.birthDate ?? "sin cargar"}{player.age !== null ? ` · ${player.age} años` : ""}</span></span><span className={`grid h-7 w-7 place-items-center rounded-full border ${present ? "border-green-500 bg-green-700 text-white" : "border-stone-600 text-stone-500"}`}>{present && <Check size={17} />}</span></button><button disabled={!editable || savingId === player.id} onClick={() => setEditingPlayer(player)} className="rounded border border-[var(--ea-border)] p-2 text-[var(--ea-gold-soft)]"><Pencil size={15} /></button></div>; })}{!players.length && <p className="p-6 text-center text-sm text-stone-500">No hay jugadores que coincidan con la búsqueda.</p>}</div></section>
    {report.permissions.canEditSheet && <section className="ea-panel rounded-lg p-4 sm:p-5"><div className="flex items-center gap-3"><Plus className="text-[var(--ea-gold)]" /><h2 className="ea-heading text-xl">Evento del partido</h2></div><form onSubmit={submitEvent} className="mt-4 grid gap-3 sm:grid-cols-2"><select disabled={!editable} required value={eventPlayerId} onChange={(event) => setEventPlayerId(event.target.value)}><option value="" disabled>Jugador presente</option>{eventPlayers.map((player) => <option key={player.id} value={player.id}>#{entries.get(player.id)?.shirtNumber ?? player.shirtNumber} · {player.name}</option>)}</select><select disabled={!editable} required value={eventTypeId} onChange={(event) => setEventTypeId(event.target.value)}><option value="" disabled>Evento</option>{report.eventTypes.map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</select><input disabled={!editable} required name="minute" type="number" min="0" max="130" placeholder="Minuto" /><input disabled={!editable} name="comments" maxLength={300} placeholder="Observación (opcional)" /><button disabled={!editable || loading || !eventPlayers.length} className="rounded-md bg-[linear-gradient(135deg,#b71920,#77080d)] px-4 py-3 text-sm font-bold text-white disabled:opacity-50 sm:col-span-2">{loading ? "Guardando..." : "Registrar evento"}</button></form></section>}
    <section className="ea-panel rounded-lg p-4 sm:p-5"><div className="flex items-center gap-3"><ClipboardCheck className="text-[var(--ea-gold)]" /><div><h2 className="ea-heading text-xl">Confirmación digital</h2><p className="text-xs text-stone-400">Finalizar partido → delegados → árbitro → veedor.</p></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{confirmationTypes.map((type) => { const item = report.confirmations.find((confirmation) => confirmation.confirmationType === type); const prerequisite = !report.matchFinishedAt ? "Pendiente: partido finalizado" : type === "REFEREE" && !delegatesConfirmed ? "Pendiente: delegados" : type === "SUPERVISOR" && !has("REFEREE") ? "Pendiente: árbitro" : ""; return <div key={type} className={`rounded-md border p-3 ${item ? "border-green-700" : "border-[var(--ea-border)]"}`}><p className={`text-sm font-bold ${item ? "text-green-300" : "text-white"}`}>{item ? `${labels[type]} confirmado` : labels[type]}</p>{item?.comments && <p className="mt-1 text-xs text-amber-100">{item.comments}</p>}{!item && <button disabled={!canConfirm(type)} onClick={() => setConfirmationType(type)} className="mt-3 w-full rounded border border-[var(--ea-gold)]/50 px-2 py-1.5 text-xs font-bold text-[var(--ea-gold-soft)] disabled:border-stone-700 disabled:text-stone-500">{canConfirm(type) ? "Confirmar" : prerequisite || "Sin permiso"}</button>}</div>; })}</div></section>
    <section className="ea-panel overflow-hidden rounded-lg"><div className="flex items-center gap-3 border-b border-[var(--ea-border)] p-4"><ScrollText className="text-[var(--ea-gold)]" /><h2 className="ea-heading text-xl">Eventos registrados</h2></div>{report.events.length ? <div className="divide-y divide-[var(--ea-border)]">{report.events.map((event) => <div key={event.id} className="flex items-center gap-3 p-3"><span className="font-bold text-[var(--ea-gold)]">{event.minute}&apos;</span><span className="min-w-0 flex-1"><span className="block font-semibold">{event.playerName} <span className="text-xs font-normal text-stone-400">· {event.eventName}</span></span>{event.comments && <span className="block text-xs text-stone-400">{event.comments}</span>}</span>{editable && <button onClick={() => setEditingEvent(event)} className="rounded border border-[var(--ea-border)] p-2 text-[var(--ea-gold-soft)]"><Pencil size={15} /></button>}</div>)}</div> : <p className="p-6 text-center text-sm text-stone-500">Todavía no hay eventos registrados.</p>}</section>
    <Dialog open={Boolean(editingPlayer)} onOpenChange={(open) => !open && setEditingPlayer(null)}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle>Datos para este partido</DialogTitle><DialogDescription>{editingPlayer?.name}. Estos datos solo se aplican a esta planilla.</DialogDescription></DialogHeader>{editingPlayer && <form onSubmit={savePlayerDetails} className="space-y-4"><label className="grid gap-1 text-sm font-medium">N° de camiseta<input name="shirtNumber" type="number" min="0" max="99" defaultValue={editingEntry?.shirtNumber ?? editingPlayer.shirtNumber} /></label><label className="flex items-center gap-2 text-sm font-medium"><input name="isStarter" type="checkbox" defaultChecked={editingEntry?.isStarter ?? false} />Titular</label><label className="flex items-center gap-2 text-sm font-medium"><input name="isCaptain" type="checkbox" defaultChecked={editingEntry?.isCaptain ?? false} />Capitán</label><label className="flex items-center gap-2 text-sm font-medium"><input name="isGoalkeeper" type="checkbox" defaultChecked={editingEntry?.isGoalkeeper ?? false} />Arquero</label><div className="flex justify-end gap-3"><button type="button" onClick={() => setEditingPlayer(null)} className="rounded-md border border-[var(--ea-border)] px-4 py-2 text-sm">Cancelar</button><button disabled={!editable || savingId === editingPlayer.id} className="rounded-md bg-[#9e1016] px-4 py-2 text-sm font-bold text-white">Guardar datos</button></div></form>}</DialogContent></Dialog>
    <Dialog open={Boolean(editingEvent)} onOpenChange={(open) => !open && setEditingEvent(null)}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle>Corregir evento</DialogTitle><DialogDescription>Permitido mientras el partido no esté finalizado.</DialogDescription></DialogHeader>{editingEvent && <form onSubmit={submitEventEdit} className="space-y-3"><select name="playerRegistrationId" defaultValue={editingEvent.playerRegistrationId} required>{eventPlayers.map((player) => <option key={player.id} value={player.id}>#{entries.get(player.id)?.shirtNumber ?? player.shirtNumber} · {player.name}</option>)}</select><select name="eventTypeId" defaultValue={editingEvent.eventTypeId} required>{report.eventTypes.map((type) => <option key={type.id} value={type.id}>{type.name}</option>)}</select><input name="minute" type="number" min="0" max="130" defaultValue={editingEvent.minute} required /><textarea name="comments" maxLength={300} defaultValue={editingEvent.comments ?? ""} placeholder="Observación (opcional)" /><div className="flex justify-end gap-3"><button type="button" onClick={() => setEditingEvent(null)} className="rounded-md border border-[var(--ea-border)] px-4 py-2 text-sm">Cancelar</button><button disabled={!editable || loading} className="rounded-md bg-[#9e1016] px-4 py-2 text-sm font-bold text-white">Guardar corrección</button></div></form>}</DialogContent></Dialog>
    <Dialog open={Boolean(confirmationType)} onOpenChange={(open) => !open && setConfirmationType(null)}><DialogContent className="sm:max-w-md"><DialogHeader><DialogTitle>Confirmar planilla</DialogTitle><DialogDescription>{confirmationType ? `${labels[confirmationType]}: se registra usuario y fecha/hora.` : ""}</DialogDescription></DialogHeader><form onSubmit={confirm} className="space-y-4"><label className="grid gap-1 text-sm font-medium">Comentario o reclamo (opcional)<textarea name="comments" maxLength={600} placeholder="Observación sobre la planilla o reclamo de puntos" /></label><div className="flex justify-end gap-3"><button type="button" onClick={() => setConfirmationType(null)} className="rounded-md border border-[var(--ea-border)] px-4 py-2 text-sm">Cancelar</button><button disabled={loading} className="rounded-md bg-[#9e1016] px-4 py-2 text-sm font-bold text-white">Confirmar</button></div></form></DialogContent></Dialog>
  </div>;
}
